### PR TITLE
fix coredump in hgraph when using empty parameter

### LINKED ISSUE #883: [0.15.0] create hgraph index crash when index_param is empty
**Describe the bug**
create hgraph index with empty index_param causes core dump

version/0.15.0

**To Reproduce**
Codes to reproduce the behavior:
```cpp
  std::string hgraph_build_parameters = R"(
    {
        "dtype": "float32",
        "metric_type": "l2",
        "dim": 128,
        "index_param": {}
    }
    )";
  ::vsag::Engine engine;
  auto index = engine.CreateIndex("hgraph", hgraph_build_parameters).value();
```

### PR DESCRIPTION
**Pull request by inabao**
closed: #883

### CODE REVIEW

**Review by wxyucs — APPROVED** [review]
lgtm

File: src/algorithm/hgraph.cpp [hunk 1]
```diff
@@ -1242,7 +1242,7 @@ static const std::string HGRAPH_PARAMS_TEMPLATE =
                 "{QUANTIZATION_TYPE_KEY}": "{QUANTIZATION_TYPE_VALUE_FP32}",
                 "{SQ4_UNIFORM_QUANTIZATION_TRUNC_RATE}": 0.05,
                 "{PCA_DIM}": 0,
-                "{PRODUCT_QUANTIZATION_DIM}": 0
+                "{PRODUCT_QUANTIZATION_DIM}": 32
```
Comment (LHT129) [inline src/algorithm/hgraph.cpp]: 1 is better, some times dim may lower than 32

Comment (inabao) [reply src/algorithm/hgraph.cpp]: done

**Review by LHT129 — APPROVED** [review]
LGTM
