### PR TITLE
fix(sindi): enable returns failed ID when inserting duplicate id

### LINKED ISSUE #1476: sindi index needs to ignore the add of duplicate ids
**Describe the bug**
When the Add function is called to add a vector to sindi, sindi does not remove duplicates for the same id. Instead, it was inserted into the index as a new vector

**To Reproduce**
Codes to reproduce the behavior:
```cpp
auto base = vsag::Dataset::Make();
base->NumElements(num_base)->SparseVectors(sv_base.data())->Ids(ids.data())->Owner(false);
auto add_res = index->Add(invalid_data);
// add same again
auto add_res = index->Add(invalid_data); 
// then index->GetNumElements() shoule be 1
```

**Environment**
Please run `bash scripts/check_environment.sh` and paste the output here:
- OS:  `5.10.134-18.al8.x86_64 GNU/Linux`
- vsag version:  `v0.16.10`
- compiler version: `GCC9`
- interface: `cpp`

**Expected behavior**
nop

**Screenshots**
nop

**Additional context**
nop

### PR DESCRIPTION
**Pull request by inabao**
close #1476

### CODE REVIEW

File: tests/test_sindi.cpp [hunk 1]
```diff
@@ -228,3 +228,12 @@ TEST_CASE_PERSISTENT_FIXTURE(fixtures::SINDITestIndex, "SINDI Serialize File", "
     }
     vsag::Options::Instance().set_block_size_limit(origin_size);
 }
+
+TEST_CASE_PERSISTENT_FIXTURE(fixtures::SINDITestIndex, "Sindi Duplicate ID Test", "[ft][sindi]") {
```
Comment (LHT129) [inline tests/test_sindi.cpp:232]: like hgraph/IVF 's test method to refactor the SINDI

**Review by LHT129 — APPROVED** [review]
LGTM

File: src/dataset_impl.cpp [hunk 2]
```diff
@@ -134,27 +134,37 @@ DatasetImpl::DeepCopy(Allocator* allocator) const {
...
-    auto* paths = new std::string[num_elements];
-    copy_dataset->Paths(paths);
-    for (int i = 0; i < num_elements; ++i) {
-        paths[i] += this->GetPaths()[i];
+    if (this->GetSparseVectors() != nullptr) {
+        copy_dataset->SparseVectors(allocate_and_copy_sparse_vectors(
+            this->GetSparseVectors(), num_elements, allocator_ref));
+    }
+    if (this->GetPaths() != nullptr) {
+        auto* paths = new std::string[num_elements];
```
[the remark this answers is not in the document]
Comment (wxyucs) [reply src/dataset_impl.cpp:163]: @inabao consider this comment

File: src/dataset_impl.cpp [hunk 3]
```diff
@@ -134,27 +134,37 @@ DatasetImpl::DeepCopy(Allocator* allocator) const {
...
+        copy_dataset->Paths(paths);
+        for (int i = 0; i < num_elements; ++i) {
+            paths[i] += this->GetPaths()[i];
```
Comment (wxyucs) [inline src/dataset_impl.cpp:166]: what is the reason to use the `+=` operator?

Comment (inabao) [reply src/dataset_impl.cpp:166]: Using the = sign is a shallow copy.

File: tests/test_sindi.cpp (hunk 1 above)
Comment (inabao) [reply tests/test_sindi.cpp:232]: i will do it in future pr

**Review by wxyucs — APPROVED** [review]
lgtm
