### PR TITLE
remove the internal default resource creation while constructing engine

### LINKED ISSUE #484: Support Create Index without Resource Pool
**Describe the bug**

When creating an index, an unexpected thread is created. 
Subsequently, other threads will be used to access this index.

**To Reproduce**
backtrace

#0  oceanbase::lib::ObUnmanagedMemoryStat::inc (this=0x555bc0d69548 <oceanbase::lib::ObUnmanagedMemoryStat::get_instance()::instance>, size=8392704) at ./deps/oblib/src/lib/alloc/alloc_struct.cpp:106
#1  0x0000555bb7f786d7 in ob_mmap (addr=0x0, length=8392704, prot=3, flags=131106, fd=-1, offset=0) at ../../../../../deps/oblib/src/lib/alloc/malloc_hook.cpp:78
#2  0x0000555bb7f77bf9 in ob_mmap_hook (addr=0x0, length=8392704, prot=3, flags=131106, fd=-1, offset=0) at ../../../../../deps/oblib/src/lib/alloc/malloc_hook.cpp:223
#3  0x00007f13abf3277d in pthread_create@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
#4  0x0000555bbf194685 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) ()
#5  0x0000555bbb53f484 in vsag::DefaultThreadPool::DefaultThreadPool(unsigned long) ()
#6  0x0000555bbb53dde1 in vsag::Resource::Resource(vsag::Allocator*, vsag::ThreadPool*) ()
#7  0x0000555bbb4e4066 in vsag::Engine::Engine(vsag::Resource*) ()
#8  0x0000555bbb5524a6 in vsag::Factory::CreateIndex(std::string const&, std::string const&, vsag::Allocator*) ()
#9  0x0000555bbb4d2c2f in obvectorlib::create_index(void*&, obvectorlib::IndexType, char const*, char const*, int, int, int, int, void*) ()

**Environment**
Please run `bash scripts/check_environment.sh` and paste the output here:
- OS: `alios 7.2`
- vsag version: `v0.13.4`
- compiler version: e.g. `GCC 9.3`
- interface: `cpp`

### PR DESCRIPTION
**Pull request by inabao**
- remove the default constructor of Engine
- provide the interface for resource creation

closes: #484

### CODE REVIEW

File: include/vsag/engine.h [hunk 1]
```diff
@@ -75,6 +68,33 @@ class Engine {
...
+     *
+     * This function attempts to create a memory allocator and returns a result which may either
+     * contain a shared pointer to the created `Allocator` or an `Error` object indicating failure
+     * conditions. This is typically used for custom memory management strategies.
+     *
+     * @return tl::expected<std::shared_ptr<Allocator>, Error> An expected value that contains either
+     * a shared pointer to the successfully created `Allocator` or an `Error` detailing
+     */
+    static tl::expected<std::shared_ptr<Allocator>, Error>
+    CreateAllocator();
```
Comment (wxyucs) [inline include/vsag/engine.h]: CreateAllocator -> CreateDefaultAllocator

File: src/stream_reader.cpp [hunk 2]
```diff
@@ -17,6 +17,8 @@
 
 #include <fmt/format-inl.h>
 
+#include <iostream>
```
Comment (wxyucs) [inline src/stream_reader.cpp]: remove if not required

File: src/engine.cpp [hunk 3]
```diff
@@ -157,6 +153,22 @@ Engine::CreateIndex(const std::string& origin_name, const std::string& parameter
         LOG_ERROR_AND_RETURNS(e.error_.type, "failed to create index: " + e.error_.message);
     }
 }
+
+tl::expected<std::shared_ptr<Allocator>, Error>
+Engine::CreateAllocator() {
+    return std::make_shared<DefaultAllocator>();
```
Comment (wxyucs) [inline src/engine.cpp:159]: return the pointer directly not expected object if this function always succeeds

File: src/resource.cpp [hunk 4]
```diff
@@ -20,19 +20,17 @@
 
 namespace vsag {
 
-Resource::Resource() : Resource(nullptr, nullptr) {
+Resource::Resource() {
+    this->allocator = SafeAllocator::FactoryDefaultAllocator();
+    this->thread_pool = SafeThreadPool::FactoryDefaultThreadPool();
 }
 
 Resource::Resource(Allocator* allocator, ThreadPool* thread_pool) {
```
Comment (wxyucs) [inline src/resource.cpp:28]: add an overload function to support pass smart pointers of allocator and thread_pool

File: src/stream_reader.cpp (hunk 2 above)
Comment (inabao) [reply src/stream_reader.cpp]: done

File: src/engine.cpp (hunk 3 above)
Comment (inabao) [reply src/engine.cpp:159]: done

File: src/resource.cpp (hunk 4 above)
Comment (inabao) [reply src/resource.cpp:28]: done

File: include/vsag/engine.h (hunk 1 above)
Comment (inabao) [reply include/vsag/engine.h]: done

File: src/safe_allocator.h [hunk 5]
```diff
@@ -77,6 +81,8 @@ class SafeAllocator : public Allocator {
 private:
     Allocator* const raw_allocator_ = nullptr;
 
+    std::shared_ptr<Allocator> const raw_allocator_shared_;
```
Comment (jiaweizone) [inline src/safe_allocator.h:84]: raw_allocator_shared_  -> shared_allocator_ ?

File: src/safe_thread_pool.h [hunk 6]
```diff
@@ -77,6 +82,7 @@ class SafeThreadPool : public ThreadPool {
 
 private:
     ThreadPool* pool_{nullptr};
+    std::shared_ptr<ThreadPool> pool_ptr_{nullptr};
```
Comment (jiaweizone) [inline src/safe_thread_pool.h:85]: pool_ -> raw_pool_
pool_ptr_ -> shared_ptr_ ?

**Review by ShawnShawnYou — APPROVED** [review]

**Review by LHT129 — APPROVED** [review]
LGTM

**Review by jiaweizone — APPROVED** [review]
