### PR TITLE
fix recall when using residual

### LINKED ISSUE #845: sq8 with IMI and residual have low recall rate problem
Image

### PR DESCRIPTION
**Pull request by inabao**
fixed: #845

### CODE REVIEW

**Review by LHT129 — APPROVED** [review]
LGTM

File: tests/test_ivf.cpp [hunk 1]
```diff
@@ -1170,17 +1170,14 @@ TestIVFGNOIMIBuildWithResidual(const fixtures::IVFTestIndexPtr& test_index,
...
-        // {"pq,fp32", 0.82},
-        // {"pqfs,fp32", 0.82},
-    };
 
     for (auto metric_type : resource->metric_types) {
         for (auto dim : resource->dims) {
             for (auto train_type : resource->train_types) {
-                for (auto& [base_quantization_str, recall] : tmp_test_cases) {
+                for (auto& [base_quantization_str, recall] : resource->test_cases) {
+                    if (base_quantization_str == "sq8_uniform,fp32") {
```
Comment (wxyucs) [inline tests/test_ivf.cpp:1223]: add comment about why need to skip this case

Comment (inabao) [reply tests/test_ivf.cpp:1223]: done

**Review by wxyucs — APPROVED** [review]
lgtm
