### PR TITLE
fix coredump for searching empty HGraph index

### LINKED ISSUE #557: KnnSearch in Hgraph without Build will cause a coredump
**Describe the bug**
there is no check in HGraph when the index is empty

**Screenshots**

Image

### LINKED ISSUE #558: loss initialization of topk in HGraph when searching high level graph
**To Reproduce**
 search_param.topk is 0 as default:
```cpp
    InnerSearchParam search_param;
    search_param.ep = this->entry_point_id_;
    search_param.ef = 1;
    search_param.is_inner_id_allowed = nullptr;
    for (auto i = static_cast<int64_t>(this->route_graphs_.size() - 1); i >= 0; --i) {
        auto result = this->search_one_graph(query->GetFloat32Vectors(),
                                             this->route_graphs_[i],
                                             this->basic_flatten_codes_,
                                             search_param);
        search_param.ep = result.top().second;
    }

```

### PR DESCRIPTION
**Pull request by inabao**
fixed: #558 
fixed: #557

### CODE REVIEW

File: src/algorithm/inner_index_interface.h [hunk 1]
```diff
@@ -111,6 +111,11 @@ class InnerIndexInterface {
                 const std::string& parameters,
                 int64_t limited_size = -1) const {
         FilterPtr filter = nullptr;
+        if (GetNumElements() == 0) {
```
Comment (jiaweizone) [inline src/algorithm/inner_index_interface.h:115]: The line L119 has already been checked, so there is no need to check here ？

Comment (inabao) [reply src/algorithm/inner_index_interface.h:115]: Line L119 is the search function within the specific index; we cannot rely on its checks.

File: src/algorithm/inner_index_interface.cpp [hunk 2]
```diff
@@ -42,6 +42,11 @@ InnerIndexInterface::KnnSearch(const DatasetPtr& query,
     if (filter != nullptr) {
         filter_ptr = std::make_shared<UniqueFilter>(filter);
     }
+    if (GetNumElements() == 0) {
+        auto result = Dataset::Make();
+        result->Dim(0)->NumElements(1);
+        return result;
+    }
```
Comment (wxyucs) [inline src/algorithm/inner_index_interface.cpp]: add a new function named `Dataset::MakeEmptyResult` and put these codes in it to avoid code repetition.

Comment (wxyucs) [reply src/algorithm/inner_index_interface.cpp]: after modified:
```cpp
if (GetNumElements() == 0) {
    return Dataset::MakeEmptyResult();
}
```

**Review by wxyucs — CHANGES_REQUESTED** [review]

File: src/algorithm/inner_index_interface.cpp (hunk 2 above)
Comment (inabao) [reply src/algorithm/inner_index_interface.cpp]: done

File: src/algorithm/hgraph.cpp [hunk 3]
```diff
@@ -254,6 +255,11 @@ HGraph::KnnSearch(const DatasetPtr& query,
                   const FilterPtr& filter,
                   IteratorContext*& iter_ctx,
                   bool is_last_filter) const {
+    if (GetNumElements() == 0) {
+        auto result = Dataset::Make();
+        result->Dim(0)->NumElements(1);
+        return result;
+    }
```
Comment (LHT129) [inline src/algorithm/hgraph.cpp:259]: why not place it on IndexImpl

File: tests/test_hgraph.cpp [hunk 4]
```diff
@@ -327,6 +327,34 @@ TEST_CASE_PERSISTENT_FIXTURE(fixtures::HgraphTestIndex,
     }
 }
 
+TEST_CASE_PERSISTENT_FIXTURE(fixtures::HgraphTestIndex,
+                             "HGraph Search Empty Index",
+                             "[ft][hgraph]") {
+    auto origin_size = vsag::Options::Instance().block_size_limit();
```
Comment (LHT129) [inline tests/test_hgraph.cpp:333]: add new test method on test_index.h and reuse on different idex

**Review by LHT129 — CHANGES_REQUESTED** [review]

File: src/algorithm/hgraph.cpp (hunk 3 above)
Comment (inabao) [reply src/algorithm/hgraph.cpp:259]: done

**Review by wxyucs — APPROVED** [review]
lgtm

**Review by LHT129 — APPROVED** [review]
LGTM
