### PR TITLE
fix(kmeans): fix kmeans unittest "0 == 161" bug

### LINKED ISSUE #1258: unittest failed in kmeans_cluster_test.cpp: 0 == 161
**Describe the bug**
```bash

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unittests is a Catch2 v3.7.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
Kmeans Basic Test
-------------------------------------------------------------------------------
/work/src/impl/cluster/kmeans_cluster_test.cpp:42
...............................................................................

/work/src/impl/cluster/kmeans_cluster_test.cpp:59: FAILED:
  REQUIRE( new_labels[i] == labels[i] )
with expansion:
  0 == 161

```

**To Reproduce**
Codes to reproduce the behavior:
```bash
make dist-cxx11-abi
```

**Environment**
Please run `bash scripts/check_environment.sh` and paste the output here:
- Image: dockcross/manylinux_2_28-x64
- vsag version: dockcross/manylinux_2_28-x64
- compiler version: 
- interface: cpp

### PR DESCRIPTION
**Pull request by LHT129**
fixed: #1258

### CODE REVIEW

**Review by inabao — APPROVED** [review]
LGTM

File: src/impl/cluster/kmeans_cluster_test.cpp [hunk 1]
```diff
@@ -26,12 +26,12 @@ GenerateDataset(int32_t k, int32_t dim, uint64_t count, std::vector<int>& labels
     labels.clear();
     labels.resize(k, 0);
 
-    auto centroids = fixtures::generate_vectors(k, dim, false, 315);
+    auto centroids = fixtures::generate_vectors(k, dim, true, 315);
```
Comment (wxyucs) [inline src/impl/cluster/kmeans_cluster_test.cpp]: add comment: generate_vectors(k, dim, /*parameter_name=*/ true, /*parameter_name=*/ 315)

File: src/impl/cluster/kmeans_cluster_test.cpp [hunk 2]
```diff
@@ -26,12 +26,12 @@ GenerateDataset(int32_t k, int32_t dim, uint64_t count, std::vector<int>& labels
...
 
     for (int64_t i = 0; i < count; ++i) {
         auto label = random() % k;
         for (int64_t j = 0; j < dim; ++j) {
-            result[i * dim + j] = centroids[label * dim + j] + 0.0002;
+            result[i * dim + j] = centroids[label * dim + j] + 0.00001F;
```
Comment (wxyucs) [inline src/impl/cluster/kmeans_cluster_test.cpp]: add a comment like `centroids[...] + /*noise=*/0.0001F`
or
constexpr float CLUSTER_POINT_NOISE = 0.00001F;

File: src/impl/cluster/kmeans_cluster_test.cpp (hunk 1 above)
Comment (LHT129) [reply src/impl/cluster/kmeans_cluster_test.cpp]: done

File: src/impl/cluster/kmeans_cluster_test.cpp (hunk 2 above)
Comment (LHT129) [reply src/impl/cluster/kmeans_cluster_test.cpp]: done

**Review by ShawnShawnYou — APPROVED** [review]
lgtm
