### PR TITLE
fix compiler issues when using clang make libcxx

### LINKED ISSUE #405: compiler issues when make libcxx using clang in 0.13
**Describe the bug**
compile error when using clang 
1. can't find std::__countr_zero 
2. fmt::format meets std::string

**To Reproduce**
```
make libcxx CMAKE_INSTALL_PREFIX=`pwd`/install
```

**Environment**
- vsag version: v0.13.1-1-ga9a0f5d9-dirty
- compiler version: c++ (GCC) 9.2.1 20200522 

**Expected behavior**
1. implement `std::__countr_zero`
2. replace `std::string param_str` with `constexpr static const char* param_str`

**Screenshots**
1. 
Image
2. 
Image

### PR DESCRIPTION
**Pull request by ShawnShawnYou**
fix #405

std::countr_zero available since C++20: https://en.cppreference.com/w/cpp/numeric/countr_zero

### CODE REVIEW

**Review by inabao — COMMENTED** [review]
add a issue

**Review by inabao — APPROVED** [review]
LGTM

**Review by wxyucs — APPROVED** [review]
lgtm

File: src/io/memory_block_io.h [hunk 1]
```diff
@@ -80,9 +80,22 @@ class MemoryBlockIO : public BasicIO<MemoryBlockIO> {
...
+            x >>= 1;
+            ++count;
+        }
+        return count;
+    }
+
     inline void
     update_by_block_size() {
-        block_bit_ = std::__countr_zero(block_size_);
+        block_bit_ = countr_zero(block_size_);
```
Comment (jiaweizone) [inline src/io/memory_block_io.h:98]: Here can change to use std::__popcount ?

Comment (ShawnShawnYou) [reply src/io/memory_block_io.h:98]: __popcount is also be available in C++20? Besides, __countr_zero is used to count the 0 from rightmost bit until the first 1, while __popcount is used to count the number of all 1.

**Review by LHT129 — APPROVED** [review]
LGTM

File: src/io/memory_block_io.h (hunk 1 above)
Comment (jiaweizone) [reply src/io/memory_block_io.h:98]: OK，`update_by_block_size` currently is O(n) cost implement, if in hot path your can change to use compiler optimize implement, like:

```C++
#pragma once
#include <type_traits>

namespace bitops {
    template <typename T>
    inline int countr_zero(T x) noexcept {
        static_assert(std::is_unsigned_v<T>, "T must be unsigned");

        if (x == 0) return sizeof(T) * 8;

        #if defined(__GNUC__)
            if constexpr (sizeof(T) <= sizeof(unsigned)) {
                return __builtin_ctz(x);
            } else if constexpr (sizeof(T) <= sizeof(unsigned long)) {
                return __builtin_ctzl(x);
            } else {
                return __builtin_ctzll(x);
            }
        #elif defined(_MSC_VER)
            unsigned long index;
            _BitScanForward(&index, x);
            return index;
        #else
            // fallback to generic O(n) implement
            int count = 0;
            while ((x & 1) == 0) {
                x >>= 1;
                ++count;
            }
            return count;
        #endif
    }
}
```

**Review by jiaweizone — APPROVED** [review]
LGTM
