### PR TITLE
fix the issue where train_data_type_ is not initialized

### LINKED ISSUE #550: evaluating performance using eval_performance on the IP dataset will causes a core dump.
**Describe the bug**
The initialization order of train_data_type_ is incorrect.

**To Reproduce**
Codes to reproduce the behavior:
```cpp

                if (obj->train_data_type_ == vsag::DATATYPE_FLOAT32) {
                    obj->distance_func_ = vsag::InnerProductDistance;
                } else if (obj->train_data_type_ == vsag::DATATYPE_INT8) {
                    obj->distance_func_ = vsag::INT8InnerProductDistance;
                }

```

**Environment**
Please run `bash scripts/check_environment.sh` and paste the output here:
- OS: Alibaba Group Enterprise Linux Server 7.2
- vsag version: v0.13.0-117-g135a5ded
- compiler version: c++ (GCC) 9.2.1 20200522 (Alibaba 9.2.1-3 2.17)

### PR DESCRIPTION
**Pull request by inabao**
fixed: #550

### CODE REVIEW

**Review by wxyucs — APPROVED** [review]
lgtm

File: tools/eval/eval_dataset.cpp [hunk 1]
```diff
@@ -272,6 +228,50 @@ EvalDataset::Load(const std::string& filename) {
         }
     }
 
+    try {
```
Comment (jiaweizone) [inline tools/eval/eval_dataset.cpp:231]: minor: the method EvalDataset::Load is too long

**Review by jiaweizone — APPROVED** [review]
LGTM
