### PR TITLE
fix(sindi): bad alloc and bench issue caused by term id limit

### LINKED ISSUE #1244: Protect bad alloc caused by resize in SINDI

### PR DESCRIPTION
**Pull request by ShawnShawnYou**
close #1244

## Summary by Sourcery

Refactor term list resizing to avoid allocation failures, enhance exception handling and logging in the SINDI algorithm, and raise the term ID limit to 10 million

Bug Fixes:
- Prevent crashes by handling std::bad_alloc during vector insertions and in term list resizing

Enhancements:
- Refactor ResizeTermList to preallocate new buffers, move existing data, and swap the new containers to improve stability
- Catch std::runtime_error by const reference and prepend context to log messages in SINDI::Add
- Increase the validated upper bound for term_id_limit from 1,000,000 to 10,000,000 in SINDIParameter

### CODE REVIEW

**Review by inabao — APPROVED** [review]
LGTM

File: src/algorithm/sindi/sindi_parameter.cpp [hunk 1]
```diff
@@ -105,7 +105,7 @@ SINDISearchParameter::FromJson(const JsonType& json) {
     if (json[INDEX_SINDI].Contains(SPARSE_QUERY_PRUNE_RATIO)) {
         query_prune_ratio = json[INDEX_SINDI][SPARSE_QUERY_PRUNE_RATIO].GetFloat();
         CHECK_ARGUMENT(
-            (0.0F <= query_prune_ratio and query_prune_ratio <= 0.5F),
+            (0.0F <= query_prune_ratio and query_prune_ratio <= 0.9F),
             fmt::format("query_prune_ratio must in [0, 0.5], got {}", query_prune_ratio));
```
Comment (wxyucs) [inline src/algorithm/sindi/sindi_parameter.cpp]: the error message is not equal to the check condition

File: src/algorithm/sindi/sindi_parameter.cpp [hunk 2]
```diff
@@ -96,7 +96,7 @@ SINDISearchParameter::FromJson(const JsonType& json) {
                    fmt::format("parameters must contains {}", INDEX_SINDI));
     if (json[INDEX_SINDI].Contains(SPARSE_TERM_PRUNE_RATIO)) {
         term_prune_ratio = json[INDEX_SINDI][SPARSE_TERM_PRUNE_RATIO].GetFloat();
-        CHECK_ARGUMENT((0.0F <= term_prune_ratio and term_prune_ratio <= 0.5F),
+        CHECK_ARGUMENT((0.0F <= term_prune_ratio and term_prune_ratio <= 0.9F),
                        fmt::format("term_prune_ratio must in [0, 0.5], got {}", term_prune_ratio));
```
Comment (wxyucs) [inline src/algorithm/sindi/sindi_parameter.cpp]: the error message is not equal to the check condition

File: src/algorithm/sindi/sindi_parameter.cpp [hunk 3]
```diff
@@ -25,15 +25,15 @@ SINDIParameter::FromJson(const JsonType& json) {
...
+            fmt::format("term_id_limit must in (0, 10'000'000], but now is {}", term_id_limit));
     } else {
         term_id_limit = DEFAULT_TERM_ID_LIMIT;
     }
 
     if (json.Contains(SPARSE_DOC_PRUNE_RATIO)) {
         doc_prune_ratio = json[SPARSE_DOC_PRUNE_RATIO].GetFloat();
-        CHECK_ARGUMENT((0.0F <= doc_prune_ratio and doc_prune_ratio <= 0.5F),
+        CHECK_ARGUMENT((0.0F <= doc_prune_ratio and doc_prune_ratio <= 0.9F),
                        fmt::format("doc_prune_ratio must in [0, 0.5], got {}", doc_prune_ratio));
```
Comment (wxyucs) [inline src/algorithm/sindi/sindi_parameter.cpp]: the error message is not equal to the check condition

**Review by wxyucs — CHANGES_REQUESTED** [review]

File: src/algorithm/sindi/sindi_parameter.cpp (hunk 1 above)
Comment (ShawnShawnYou) [reply src/algorithm/sindi/sindi_parameter.cpp]: done

File: src/algorithm/sindi/sindi_parameter.cpp (hunk 2 above)
Comment (ShawnShawnYou) [reply src/algorithm/sindi/sindi_parameter.cpp]: done

File: src/algorithm/sindi/sindi_parameter.cpp (hunk 3 above)
Comment (ShawnShawnYou) [reply src/algorithm/sindi/sindi_parameter.cpp]: done

**Review by wxyucs — APPROVED** [review]
lgtm
