### PR TITLE
fix: remove invalid thirdparty header files installation path

### LINKED ISSUE #1227: CMake Error occurs during binary package packaging
**Describe the bug**
```bash
...
[100%] Linking CXX executable unittests
gmake[3]: Leaving directory `/work/build-release'
[100%] Built target unittests
gmake[2]: Leaving directory `/work/build-release'
gmake[1]: Leaving directory `/work/build-release'
cmake --install "./build-release/"/
-- Install configuration: "Release"
-- Installing: /tmp/vsag/lib/libdiskann.a
-- Installing: /tmp/vsag/lib/libcpuinfo.a
CMake Error at build-release/cmake_install.cmake:72 (file):
  file INSTALL destination: /dev/null is not a directory.


make: *** [install] Error 1
[1]  + 312574 exit 2     nohup bash ./scripts/release/dist.sh > /tmp/dist.log 2>&1
```
Codes introduced in #1193, and these codes work in the development environment but not in the distribution environment:
```
install (
  TARGETS cpuinfo
  ARCHIVE DESTINATION lib
+  # we don't need this, but CMake is always warning
+  PUBLIC_HEADER DESTINATION /dev/null
)
```

**To Reproduce**
Codes to reproduce the behavior:
```bash
nohup bash ./scripts/release/dist.sh > /tmp/dist.log 2>&1
```

### PR DESCRIPTION
**Pull request by wxyucs**
fixes: #1227

## Summary by Sourcery

Bug Fixes:
- Remove PUBLIC_HEADER DESTINATION /dev/null from the cpuinfo install block in extern/cpuinfo/cpuinfo.cmake

### CODE REVIEW

**Review by LHT129 — APPROVED** [review]
LGTM

File: tests/test_simple_index.cpp [hunk 1]
```diff
@@ -146,10 +147,11 @@ TEST_CASE("Test Simple Index", "[ft][simple_index]") {
     std::vector<MergeUnit> units;
     REQUIRE_THROWS(index->Merge(units));
 
-    std::ofstream o_file("1234", std::ios::binary);
+    fixtures::TempDir dir("test_simple_index");
```
Comment (wxyucs) [inline tests/test_simple_index.cpp:150]: avoid creating a test file in the current directory (usually in the root directory of the project, making the workspace dirty)

**Review by LHT129 — APPROVED** [review]
LGTM

**Review by inabao — APPROVED** [review]
LGTM

**Review by jiaweizone — APPROVED** [review]
LGTM
