### PR TITLE
fix hnsw core dump when destructing

### LINKED ISSUE #688: core dump when simultaneously destructing and adding in HNSW
#650

### PR DESCRIPTION
**Pull request by ShawnShawnYou**
close #688

### CODE REVIEW

File: include/vsag/index.h [hunk 1]
```diff
@@ -35,6 +35,13 @@
 
 namespace vsag {
 
+enum class VSAGIndexStatus : int {
+    // start with -1
+
+    DESTRUCT = -1,  // index is destructing
```
Comment (jiaweizone) [inline include/vsag/index.h]: DESTRUCT  -> DESTROYED

File: src/index/hnsw.h [hunk 2]
```diff
@@ -54,6 +54,9 @@ class HNSW : public Index {
     HNSW(HnswParameters hnsw_params, const IndexCommonParam& index_common_param);
 
     virtual ~HNSW() {
+        this->index_status = VSAGIndexStatus::ALIVE;
```
Comment (jiaweizone) [inline src/index/hnsw.h]: this->index_status = VSAGIndexStatus::DESTORYED ?

File: src/index/hnsw.cpp [hunk 3]
```diff
@@ -119,7 +119,15 @@ HNSW::build(const DatasetPtr& base) {
 
         int64_t num_elements = base->GetNumElements();
 
+        if (not this->IsValidStatus()) {
```
Comment (jiaweizone) [inline src/index/hnsw.cpp]: status check is first step (move to L109) and in here need take the read-lock, in destructor function to take write-lock and change status to `DESTROYED`, like this: 

```C++
void HNSW::build( ... ) {
    std::shared_lock status_lock(status_mutex_);
    if (not this->IsValidStatus()) {
        LOG_ERROR_AND_RETURNS( ... );
    }
    // do index build ....
}

void HNSW:: knn_search( ... ) {
    std::shared_lock status_lock(status_mutex_);
    if (not this->IsValidStatus()) {
        LOG_ERROR_AND_RETURNS( ... );
    }
    // do index build ....
}

~HNSW() {
    std::unique_lock status_lock(status_mutex_);
    // change status to DESTROYED
    index_status = VSAGIndexStatus::DESTROYED;
    // do destroy logic ....
}
```

File: src/index/hnsw.h [hunk 4]
```diff
@@ -54,6 +54,9 @@ class HNSW : public Index {
...
+        std::unique_lock lock(rw_mutex_);
+
         alg_hnsw_ = nullptr;
         if (use_conjugate_graph_) {
             conjugate_graph_.reset();
```
Comment (jiaweizone) [inline src/index/hnsw.h:71]: Wait all bg-threads completed before release any resources ?

Comment (jiaweizone) [inline src/index/hnsw.h:71]: Wait all bg-threads completed before release any resource ?

Comment (ShawnShawnYou) [reply src/index/hnsw.h:71]: right, we use this->index_status to stop any threads after destruction. And use the lock to wait the un-finish threads

File: src/index/hnsw.cpp (hunk 3 above)
Comment (ShawnShawnYou) [reply src/index/hnsw.cpp]: fixed

File: src/index/hnsw.h (hunk 2 above)
Comment (ShawnShawnYou) [reply src/index/hnsw.h]: fixed

File: include/vsag/index.h (hunk 1 above)
Comment (ShawnShawnYou) [reply include/vsag/index.h]: fixed

File: include/vsag/index.h [hunk 5]
```diff
@@ -35,6 +35,13 @@
 
 namespace vsag {
 
+enum class VSAGIndexStatus : int {
+    // start with -1
+
+    DESTROYED = -1,  // index is destructing
+    ALIVE            // index is alive
+};
+
```
Comment (inabao) [inline include/vsag/index.h]: Why do these states need to be controlled by user rather than by self index?

File: src/index/hnsw.cpp [hunk 6]
```diff
@@ -105,6 +105,12 @@ HNSW::HNSW(HnswParameters hnsw_params, const IndexCommonParam& index_common_para
 
 tl::expected<std::vector<int64_t>, Error>
 HNSW::build(const DatasetPtr& base) {
+    std::shared_lock status_lock(index_status_mutex_);
+    if (not this->IsValidStatus()) {
+        LOG_ERROR_AND_RETURNS(
+            ErrorType::WRONG_STATUS, "index is in the wrong status({})", PrintStatus());
```
Comment (inabao) [inline src/index/hnsw.cpp:111]: can give the specific description instead of just a wrong status?

File: src/index/hnsw.cpp [hunk 7]
```diff
@@ -152,6 +158,12 @@ HNSW::build(const DatasetPtr& base) {
 
 tl::expected<std::vector<int64_t>, Error>
 HNSW::add(const DatasetPtr& base) {
+    std::shared_lock status_lock(index_status_mutex_);
+    if (not this->IsValidStatus()) {
+        LOG_ERROR_AND_RETURNS(
+            ErrorType::WRONG_STATUS, "index is in the wrong status({})", PrintStatus());
```
Comment (inabao) [inline src/index/hnsw.cpp:164]: ditto

File: src/index/hnsw.cpp [hunk 8]
```diff
@@ -192,6 +204,12 @@ HNSW::knn_search_internal(const DatasetPtr& query,
                           int64_t k,
                           const std::string& parameters,
                           const FilterType& filter_obj) const {
+    std::shared_lock status_lock(index_status_mutex_);
+    if (not this->IsValidStatus()) {
+        LOG_ERROR_AND_RETURNS(
+            ErrorType::WRONG_STATUS, "index is in the wrong status({})", PrintStatus());
```
Comment (inabao) [inline src/index/hnsw.cpp:210]: ditto

File: src/index/hnsw.cpp [hunk 9]
```diff
@@ -330,6 +347,12 @@ HNSW::range_search_internal(const DatasetPtr& query,
                             const std::string& parameters,
                             const FilterType& filter_obj,
                             int64_t limited_size) const {
+    std::shared_lock status_lock(index_status_mutex_);
+    if (not this->IsValidStatus()) {
+        LOG_ERROR_AND_RETURNS(
+            ErrorType::WRONG_STATUS, "index is in the wrong status({})", PrintStatus());
```
Comment (inabao) [inline src/index/hnsw.cpp:353]: ditto

File: src/index/hnsw.cpp (hunk 6 above)
Comment (ShawnShawnYou) [reply src/index/hnsw.cpp:111]: PrintStatus() has already give information about the status ?

File: include/vsag/index.h (hunk 5 above)
Comment (ShawnShawnYou) [reply include/vsag/index.h]: moved to hnsw.h

**Review by inabao — APPROVED** [review]
LGTM

**Review by LHT129 — APPROVED** [review]
LGTM

**Review by wxyucs — APPROVED** [review]
lgtm

**Comment by wxyucs** [comment]
conflict with branch 0.13, cannot cherry-pick directly
