### PR TITLE
resolve not properly handling invalid IDs in CalDistanceById

### LINKED ISSUE #725: hgraph 对于不存在 vid ， cal_distance_by_id接口返回的距离值 不为 -1
**Describe the bug**
hgraph 对于不存在 vid ， cal_distance_by_id接口返回的距离值 不为 -1，为一个特殊值 ，但hnsw返回结果为 -1

**To Reproduce**
Codes to reproduce the behavior:
```cpp
// paste codes here

```

**Environment**
Please run `bash scripts/check_environment.sh` and paste the output here:
- OS: e.g. `Ubuntu 22.04`
- vsag version: e.g. `v0.11.0` or `7f94a27`
- compiler version: e.g. `GCC 11.4.0`
- interface: `cpp` or `python`

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by inabao**
close: #725

### CODE REVIEW

File: src/algorithm/hgraph.cpp [hunk 1]
```diff
@@ -736,18 +736,22 @@ HGraph::CalDistanceById(const float* query, const int64_t* ids, int64_t count) c
...
             auto iter = this->label_table_->label_remap_.find(ids[i]);
             if (iter == this->label_table_->label_remap_.end()) {
                 logger::debug(fmt::format("failed to find id: {}", ids[i]));
-                distances[i] = -1;
+                invalid_id_loc.push_back(i);
                 continue;
             }
             inner_ids[i] = iter->second;
         }
         flat->Query(distances, computer, inner_ids.data(), count);
```
Comment (jiaweizone) [inline src/algorithm/hgraph.cpp:751]: because Query need original `distances` ?

Comment (inabao) [reply src/algorithm/hgraph.cpp:751]: The assignment of 'distance' is delayed here because assigning it earlier would be overwritten by the query process

**Review by LHT129 — APPROVED** [review]
LGTM

**Review by wxyucs — APPROVED** [review]
lgtm
